const sidebars = {
  // https://docusaurus.io/zh-CN/docs/sidebar/autogenerated
  self: [
    {
      type: 'doc',
      label: '自我',
      id: 'self/readme',
    },
    {
        type: 'category',
        label: '心智',
        items: [
            {
              type: 'doc',
              label: '幸福: 从 活着 到 活得好',
              id: 'self/mind/happiness',
            },
        ]
    },
    {
      type: 'category',
      label: '健康',
      items: [
        {
          type: 'doc',
          label: '身体健康',
          id: 'self/health/physical/readme',
        },
      ]
    },
  ],
  society: [
    {
      type: 'doc',
      label: '社会',
      id: 'society/readme',
    },
    {
      type: 'doc',
      label: '经济',
      id: 'society/economy/readme',
    },
  ],
};

module.exports = sidebars;
