const sidebars = {
  // https://docusaurus.io/zh-CN/docs/sidebar/autogenerated
  self: [
    {
      type: 'doc',
      label: '自我',
      id: 'self/readme',
    },
    {
      type: 'doc',
      label: '从 活着 到 活得好',
      id: 'self/speed-to-happiness',
    },
    
  ],
  society: [
  ],
};

module.exports = sidebars;
