const sidebars = {
  // https://docusaurus.io/zh-CN/docs/sidebar/autogenerated
  self: [
    {
      type: 'doc',
      label: '自我',
      id: 'self/readme',
    },
    {
        type: 'category',
        label: '心智',
        items: [
            {
            type: 'doc',
            label: '幸福: 从 活着 到 活得好',
            
            id: 'self/mind/happiness',
            },
        ]
    }
  ],
  society: [
  ],
};

module.exports = sidebars;
