const base = require('./partial/base')
const self = require('./partial/self')
const society = require('./partial/society')

// https://docusaurus.io/zh-CN/docs/sidebar/autogenerated

const sidebars = {
  base,
  self,
  society,
};

module.exports = sidebars;
